# Generated by Django 4.1.5 on 2023-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='mail',
            field=models.EmailField(default=0, max_length=254, verbose_name='Ваш Email'),
            preserve_default=False,
        ),
    ]
