# Generated by Django 4.1.5 on 2023-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('Place', models.CharField(max_length=50, verbose_name='Место путешествия')),
                ('full_text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateField(verbose_name='Дата путешествия')),
                ('score', models.IntegerField(verbose_name='Оценка')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
